apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../../base/base-app

commonLabels:
  environment: dev

images:
  - name: base-app
    newTag: latest
