kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: base-app
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # base-app
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # echo-service
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      # ArgoCD UI
      - containerPort: 30443
        hostPort: 8443
        protocol: TCP
      # Vault UI (optional)
      - containerPort: 30820
        hostPort: 8200
        protocol: TCP
      # PostgreSQL (for local development)
      - containerPort: 30432
        hostPort: 5432
        protocol: TCP
