apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/external-secrets

namespace: external-secrets

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: vault-token
    literals:
      - token=dev-root-token-change-in-production
