apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    app: echo-service
spec:
  type: NodePort
  selector:
    app: echo-service
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30081
