apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-external-secret
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/data/postgresql
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/data/postgresql
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_DB
      remoteRef:
        key: secret/data/postgresql
        property: POSTGRES_DB
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: secret/data/postgresql
        property: POSTGRES_HOST
    - secretKey: POSTGRES_PORT
      remoteRef:
        key: secret/data/postgresql
        property: POSTGRES_PORT
