apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../../base/echo-service

commonLabels:
  environment: dev

images:
  - name: echo-service
    newTag: latest
