apiVersion: v1
kind: Service
metadata:
  name: base-app
  labels:
    app: base-app
spec:
  type: NodePort
  selector:
    app: base-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
