apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-secret-store.yaml

commonLabels:
  app.kubernetes.io/part-of: accounting-system
  app.kubernetes.io/managed-by: argocd
